service: Nike-CircleCi-Lambda
custom:
  stage: ${opt:stage, self:provider.stage}
  stageConfig:
    dev:
      ucName: Dev
      domain: Nike-CircleCi-Lambda.COM
   
plugins:
  - serverless-plugin-custom-domain

provider:
  name: aws
  runtime: python2.7
  
  stage: dev
  region: us-west-2
  profile: support-circle-ci
  environment:
    NODE_ENV: ${self:custom.stage}

functions:
  switchboard1_func1:
  incoming:
   handler: switchboard._airflow_request
events:
      - http:
        path: ${self:custom.stage}/Nike-CircleCi-Lambda
        method: post
          
switchboard2_func2:
  incoming:
   handler: switchboard._em7_message_check_file_system
events:
       - http:
         path: ${self:custom.stage}/Nike-CircleCi-m7_message_check_file_system
         method: post


package:
  exclude:
    - '.*'
    - 'postman/**'
    - 'package.json'
